name: talkative
description: "Talkative - The most advanced and secure chat application that revolutionizes communication with cutting-edge features, end-to-end encryption, AI integration, and seamless user experience."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.13.6
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # UI packages
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.8
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  
  # Utility packages
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Media packages
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  camera: ^0.10.5+5
  
  # QR Code packages
  ai_barcode_scanner: ^5.1.1  # Modern scanner
  qr_flutter: ^4.1.0          # QR code generator
  
  # Communication packages
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  
  # Other packages
  intl: ^0.18.1
  uuid: ^4.2.1
  emoji_picker_flutter: ^1.6.4
  flutter_contacts: ^1.1.7+1
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.2.0
  
  # Development packages
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Add custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
  # Add assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/